### ISSUE TITLE
How to compile android  ios and macos?

### ISSUE THREAD

**Issue by zuowanbushiwo** [freckled-dev/conan-google-webrtc#4]
Are there any relevant compilation instructions? I didn't find the relevant profiles file?
Thanks！

**Comment by qwertzui11** [comment]
Hi!

checkout the *[create packages and upload them](https://github.com/freckled-dev/conan-google-webrtc/issues/4#create-packages-and-upload-them)* section. It's simply a `conan create .`

Some example profiles are available under the folder *[profiles](https://gitlab.com/acof/webrtc-conan/-/tree/master/profiles)*.
You can find more information about profiles [at the official documentation](https://docs.conan.io/en/latest/reference/profiles.html)

**Comment by zuowanbushiwo** [comment]
Thanks！
